### ISSUE TITLE
Command for Turing Machine names

### ISSUE THREAD

**Issue by aducharme** [bbchallenge/bbchallenge-paper#1]
The dashes and underscores in our standard string format for TMs (e.g. 1RB1RA_0LC1LE_1LD1LC_1LA0LB_1LF1RE_---0RA) is not LateX friendly. Putting slashes in front of every underscore gets them to show up, but in addition to being annoying, doesn't work for dashes.

**Comment by UncombedCoconut** [comment]
I've noticed that hyperref's \url{} handles the formatting brilliantly, so we "only" have to replicate what it's doing in a macro like \tm{} or \tmtext{}.
